### ISSUE TITLE
Pod install fail - Podspec

### ISSUE THREAD

**Issue by huextrat** [audienzzag/react-native-audienzz#1] opened 2021-12-14 11:39 UTC
Hi,

Thanks for this new release, the following line in the podspec will give an error during `pod install` as `mraid.js` file does not exist after importing the dependency through `npm` or `yarn`.

https://github.com/audienzzag/react-native-audienzz/blob/0213ce8760754d2d2d161d8c9f9bb091e8a55044/react-native-audienzz.podspec#L22

![Capture d’écran 2021-12-14 à 12 38 28](https://user-images.githubusercontent.com/22995315/145991365-e569a1a4-c6c4-4756-afa8-2df7a66e799a.png)

**Comment by alex-ragin** [comment] 2021-12-15 16:20
Hi @huextrat,

Thanks for your report. This is a known bug and we're releasing a new version today, where this will be fixed. This is caused by a fix of a bug in native AppNexus SDK preventing videos playback on iOS 13.+.

**Comment by alex-ragin** [comment] 2021-12-15 23:32
Hi @huextrat, please check out the latest version (0.3.4), the issue should be fixed there. 

Feel free to reopen the issue if it still doesn't compile.

**Closed by alex-ragin** 2021-12-15 23:32 UTC
Labels: bug
